name: Test-Code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - '*'         # matches every branch
      - '!main'   # excludes main    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Installs Node js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install pnpm
        run: npx pnpm add -g pnpm@7.5.0

      - name: Install dependencies
        run: pnpm install 
        
      - name: Lints
        run: npx eslint **/*.jsx

  test:
    needs: lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Installs Node js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: pnpm install 
        
      - name: Run unit tests
        run: CI=true pnpm test

      - name: Run integration tests
          # start the server in the background
        run: pnpm start & pnpm cy:run